### ISSUE TITLE
Bug discovered in trying to convert to lume 2 / VTO

### ISSUE THREAD

**Issue by UppaJung** [lumeland/base-blog#14]
https://github.com/lumeland/base-blog/blob/aeb5bc1fd3a9cbf353e6fe4cfa1c83dc2bb62b7d/_includes/templates/postslist.njk#L4C63-L4C68

From my reading, it appears that `entry.data.url == url` should be `post.data.url == url`.

**Comment by oscarotero** [comment]
Thank you! I just changed it.
