### ISSUE TITLE
add feat(style): dark mode

### ISSUE THREAD

**Issue by AugustinMauroy** [lumeland/base-blog#9]
I propose to add a dark mode that would work with the media query

**Comment by oscarotero** [comment]
You might take a look to https://github.com/lumeland/theme-simple-blog, an evolution of this base-blog template that can be installed like a plugin and have dark mode.

**Comment by AugustinMauroy** [comment]
Yes, thank you I have seen and use. What I proposed is to add it to this template so that it is as complete as possible.
